### ISSUE TITLE
switching to next/last day via swiping left/right on a device with a touch screen

### ISSUE THREAD

**Issue by MrFincher** [reclaimingmytime/schedule#1]
would make the application more immersive.

i was told this could possibly be implemented using j query ;D

maybe one could also include more gestures for other controls like changing the week

**Comment by reclaimingmytime** [comment]
Thanks for the suggestion. I definitely agree about the immersiveness.

I have now added the gestures "swipe left" and "swipe right" for "next day" and "previous day".

The plugin I'm using currently also detects "swipe up" and "swipe down". I didn't use these gestures on purpose because that detects scrolling as a swipe. :smile:
